services:
  mysql:
    image: mysql:latest
    container_name: mysql_${APPS_SLUG}_${ENV}
    environment:
      - MYSQL_DATABASE=${DATABASE_MYSQL_NAME}
      - MYSQL_USER=${DATABASE_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Jakarta
    ports:
      - 3307:3306
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_${APPS_SLUG}_${ENV}
    environment:
      - REDIS_ARGS=--user ${DATABASE_CACHE_REDIS_USERNAME} on +@all ~* >${DATABASE_CACHE_REDIS_PASSWORD} --requirepass ${DATABASE_CACHE_REDIS_PASSWORD}
    ports:
      - 6380:6379
    restart: on-failure
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app_${APPS_SLUG}_${ENV}
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      target: build-release-stage
      args:
        ENV: ${ENV}
        PORT: ${SERVER_PORT}
    ports:
      - 8081:${SERVER_PORT}
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend

volumes:
  mysql_data:
    external: true
    name: mysql_data_${APPS_SLUG}_${ENV}
  redis_data:
    external: true
    name: redis_data_${APPS_SLUG}_${ENV}

# Networks to be created to facilitate communication between containers
networks:
  backend:
    external: true
    name: backend_${APPS_SLUG}_${ENV}
