// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package permission

import (
	"github.com/rodericusifo/employee-management-api/internal/app/core/permission/resource"
	"github.com/rodericusifo/employee-management-api/internal/app/repository/database/sql/permission"
	"github.com/rodericusifo/employee-management-api/internal/pkg/util/getter"
)

// Injectors from wire.go:

func PermissionResource() resource.IPermissionResource {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iPermissionDatabaseSQLRepository := permission.InitMysqlPermissionDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iPermissionResource := resource.InitPermissionResource(iPermissionDatabaseSQLRepository)
	return iPermissionResource
}
