// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"github.com/rodericusifo/employee-management-api/internal/app/core/role/resource"
	"github.com/rodericusifo/employee-management-api/internal/app/repository/database/sql/role"
	"github.com/rodericusifo/employee-management-api/internal/pkg/util/getter"
)

// Injectors from wire.go:

func RoleResource() resource.IRoleResource {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iRoleDatabaseSQLRepository := role.InitMysqlRoleDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iRoleResource := resource.InitRoleResource(iRoleDatabaseSQLRepository)
	return iRoleResource
}
