// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package employee

import (
	"github.com/rodericusifo/employee-management-api/internal/app/core/employee/resource"
	"github.com/rodericusifo/employee-management-api/internal/app/core/employee/service"
	"github.com/rodericusifo/employee-management-api/internal/app/repository/database/sql/employee"
	"github.com/rodericusifo/employee-management-api/internal/pkg/util/getter"
)

// Injectors from wire.go:

func EmployeeService() service.IEmployeeService {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iEmployeeDatabaseSQLRepository := employee.InitMysqlEmployeeDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iEmployeeResource := resource.InitEmployeeResource(iEmployeeDatabaseSQLRepository)
	iEmployeeService := service.InitEmployeeService(iEmployeeResource)
	return iEmployeeService
}
