// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role_permission

import (
	"github.com/rodericusifo/employee-management-api/internal/app/core/role_permission/resource"
	"github.com/rodericusifo/employee-management-api/internal/app/repository/database/sql/role_permission"
	"github.com/rodericusifo/employee-management-api/internal/pkg/util/getter"
)

// Injectors from wire.go:

func RolePermissionResource() resource.IRolePermissionResource {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iRolePermissionDatabaseSQLRepository := role_permission.InitMysqlRolePermissionDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iRolePermissionResource := resource.InitRolePermissionResource(iRolePermissionDatabaseSQLRepository)
	return iRolePermissionResource
}
